# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0003_auto_20160419_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigineFonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofid', models.CharField(max_length=100)),
                ('ofparent', models.CharField(max_length=100)),
                ('ofname', models.CharField(max_length=100)),
                ('oflabel', models.CharField(max_length=100)),
                ('oftype', models.CharField(max_length=100)),
                ('ofbudget', models.CharField(max_length=100)),
                ('ofnomades', models.CharField(max_length=100)),
            ],
        ),
    ]
