# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0004_originefonds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('parentid', models.CharField(max_length=100)),
                ('ordre', models.CharField(max_length=100)),
                ('niv', models.CharField(max_length=100)),
                ('bloq', models.CharField(max_length=100)),
                ('modifdate', models.CharField(max_length=100)),
                ('modifpar', models.CharField(max_length=100)),
                ('dfmc', models.CharField(max_length=100)),
                ('fdr', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CentreFinancier',
        ),
        migrations.RemoveField(
            model_name='planfinancement',
            name='myid',
        ),
        migrations.RemoveField(
            model_name='planfinancement',
            name='parent',
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='ccassoc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='cleregul',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='cpassoc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='divirecette',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='domainefonc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='dordre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='responsable',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='societe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planfinancement',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
