# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0006_auto_20160420_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.CharField(max_length=100)),
                ('montant', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=100)),
                ('cptdep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.CompteComptable')),
                ('domfonc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.DomaineFonctionnel')),
                ('orfonds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.OrigineFonds')),
                ('plfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.PlanFinancement')),
                ('struct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.Structure')),
            ],
        ),
    ]
