# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0007_depense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.CharField(max_length=100)),
                ('montant', models.CharField(max_length=100)),
                ('commentaire', models.CharField(blank=True, max_length=100, null=True)),
                ('cptdeplev1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cptdeplev1', to='budgetweb.CompteComptable')),
                ('cptdeplev2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cptdeplev2', to='budgetweb.CompteComptable')),
                ('domfonc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.DomaineFonctionnel')),
                ('orfonds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.OrigineFonds')),
                ('plfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetweb.PlanFinancement')),
                ('structlev1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structlev1', to='budgetweb.Structure')),
                ('structlev2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structlev2', to='budgetweb.Structure')),
            ],
        ),
        migrations.AlterField(
            model_name='depense',
            name='commentaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
