# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0008_auto_20160429_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensefull',
            name='orfonds2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orfonds2', to='budgetweb.OrigineFonds'),
        ),
        migrations.AddField(
            model_name='depensefull',
            name='structlev3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structlev3', to='budgetweb.Structure'),
        ),
        migrations.AlterField(
            model_name='depensefull',
            name='orfonds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orfonds', to='budgetweb.OrigineFonds'),
        ),
    ]
