# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0009_auto_20170518_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureauthorizations',
            name='structures',
            field=models.ManyToManyField(related_name='authorized_structures', to='structure.Structure', verbose_name='structures'),
        ),
        migrations.AlterField(
            model_name='structuremontant',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure', verbose_name='structure'),
        ),
    ]
