# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0009_auto_20160504_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensefull',
            name='dateae',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depensefull',
            name='montantae',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depensefull',
            name='montantcp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depensefull',
            name='montantdc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='depensefull',
            name='montant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
