# Generated by Django 2.2.24 on 2021-10-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0010_auto_20191003_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='structure',
        ),
    ]
