# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0011_recettefull'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('annee', models.DateField(null=True)),
                ('bloque', models.BooleanField(default=True)),
            ],
        ),
    ]
