# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0012_periodebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensefull',
            name='periodebudget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodebudget1', to='budgetweb.PeriodeBudget'),
        ),
        migrations.AddField(
            model_name='recettefull',
            name='periodebudget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodebudget2', to='budgetweb.PeriodeBudget'),
        ),
    ]
