# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgetweb', '0013_auto_20160506_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensefull',
            name='creele',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 13, 13, 31, 36, 611285, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depensefull',
            name='creepar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='depensefull',
            name='modifiele',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 13, 13, 31, 58, 51196, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depensefull',
            name='modifiepar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recettefull',
            name='creele',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 13, 13, 32, 1, 331194, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recettefull',
            name='creepar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recettefull',
            name='modifiele',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 13, 13, 32, 5, 523174, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recettefull',
            name='modifiepar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
