# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfinancement',
            name='centrecoutderive',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Related cost center'),
        ),
        migrations.AlterField(
            model_name='planfinancement',
            name='centreprofitderive',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Related profit center'),
        ),
    ]
